# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # #Nome da Imagem que será baixada
    #config.vm.box = "debian/bookworm64"
    config.vm.box = "bento/debian-12"
    config.vm.box_check_update = false #Verificar o update da vbox
    config.vm.network "public_network", bridge: "default", type: "dhcp"
    config.vm.synced_folder "files", "/vagrant" 
   
    config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
     
       nomeMaquina="debianhd"
       sdb = "disks/debianhdsdb.vdi"

       if File.exist?(sdb)
        #  vb.customize ['createhd', '--filename', sdb, '--size', 10 * 1024]
          vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', sdb]
      else
        vb.customize ['createhd', '--filename', sdb, '--size', 10 * 1024]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', sdb] 
      end
     
       
       vb.name = nomeMaquina #Definindo o nome da Máquina
       vb.cpus = 1 
       vb.gui = false 
       vb.memory = "1024" 
       vb.customize ["modifyvm", :id, "--groups", "/Lab02"]
    end
    config.vm.provision "shell", inline: <<-SHELL #executando update do Debian durante o provisionamento. 
    #   hostnamectl set-hostname DebianLuks
    #   apt-get update -y
    #   apt install -y xfsprogs cryptsetup ecryptfs-utils
    #   #mkfs.xfs /dev/sdb
    #   #mkfs.xfs /dev/sdc
    #   mkdir /sdb
    #   mkdir /sdc
    #   #echo -n "YES" | cryptsetup luksFormat /dev/sdb
    #   #echo -n "YES" | cryptsetup luksFormat /dev/sdc
      #cat /files/tofstab.txt >> /etc/fstab
      #systemctl daemon-reload
      #mount -a
    SHELL
    # config.vm.provision "shell", path:"files/makedb.sh"
 end